app_name: "StockFlow 出入库系统"
database_path: "./data/stockflow.db"

features:
  multi_warehouse: true
  batch_enabled: false
  expiry_enabled: false

security:
  secret_key: "CHANGE_ME_TO_A_RANDOM_LONG_STRING"  # 用 openssl rand -hex 32 生成
  access_token_minutes: 30
  refresh_token_days: 14
  cookie_name: "sf_session"

logging:
  level: "INFO"

paths:
  event_log_dir: "./logs"
  snapshots_dir: "./snapshots"
  backups_dir: "./backups"
